profiles:
  - profiles::cluster::common
  - profiles::network::base
  - profiles::dns::client
  - profiles::auth::client
  - profiles::ntp::client
  - profiles::ssmtp::client
  - profiles::access::base
  - profiles::sudo::base
  - profiles::jobsched::exec

network::mlx4load:                'no'
profiles::network::gw_connect:    'administration'
sssd_case_sensitive:             'false'
certificates::certificates_owner: 'root'
